INDEXES_DIR = 'data/indexes'
OVERFLOW_AREA_DIR = 'data/overflow_area'
PRIMARY_AREA_DIR = 'data/primary_area'

BLOCK_SIZE = 256
KEY_SIZE = 5
RECORD_SIZE = 10
PAGE_NUMBER_SIZE = 4
OVERFLOW_POINTER_SIZE = 4

ALPHA = 0.4
FORCE_SAVE = False
